Service Reset Password URL
digi-serve/ab-cli pull request #32
Opened 2022-05-03 04:44 UTC by guyyoo

Add the input property "url" for admin and tenant

2022-05-04 07:31 UTC, wongpratan commented on lib/tasks/tenantAdd.js
> +               return !values.url && typeof Options.url == "undefined";
`typeof Options.url == "undefined"`

Should validate when Options.url is `null` ?

2022-05-05 05:00 UTC, wongpratan approved these changes

2022-05-05 09:17 UTC, Hiro-Nakamura requested changes

2022-05-05 09:17 UTC, Hiro-Nakamura commented on lib/install.js
> +    --tenant.url    [string] : the default tenant admin url
space this out so that all the `:`  line up.

2022-05-05 09:17 UTC, Hiro-Nakamura commented on lib/tasks/configTenantAdmin.js
> +            default: `http://localhost:80`,
let's make this default more descriptive for the live tenant:  `https://[tenantKey].site.url`

2022-05-05 09:17 UTC, Hiro-Nakamura commented on lib/tasks/tenantAdd.js
> +            default: "",
use a good sample url here: `https://[tenantKey].site.url`

2022-05-10 02:44 UTC, Hiro-Nakamura approved these changes
LGTM

2022-05-10 03:30 UTC, merged