fix stack name in dbinit-compose.yml
digi-serve/ab-cli pull request #55
Opened 2023-07-06 07:51 UTC by nh758

Fixes an error when stack name was different then the folder name
```
Error: (root) Additional property name is not allowed

    at tryIt (C:\Users\Nate\AppData\Roaming\nvm\v18.16.1\node_modules\ab-cli\lib\utils\dockerStackWatch.js:135:43)
    at C:\Users\Nate\AppData\Roaming\nvm\v18.16.1\node_modules\ab-cli\lib\utils\dockerStackWatch.js:141:16
    at C:\Users\Nate\AppData\Roaming\nvm\v18.16.1\node_modules\ab-cli\node_modules\async\dist\async.js:3883:24
    at replenish (C:\Users\Nate\AppData\Roaming\nvm\v18.16.1\node_modules\ab-cli\node_modules\async\dist\async.js:1014:17)
    at C:\Users\Nate\AppData\Roaming\nvm\v18.16.1\node_modules\ab-cli\node_modules\async\dist\async.js:1019:9
    at eachOfLimit (C:\Users\Nate\AppData\Roaming\nvm\v18.16.1\node_modules\ab-cli\node_modules\async\dist\async.js:1044:24)
    at C:\Users\Nate\AppData\Roaming\nvm\v18.16.1\node_modules\ab-cli\node_modules\async\dist\async.js:1049:16
    at _parallel (C:\Users\Nate\AppData\Roaming\nvm\v18.16.1\node_modules\ab-cli\node_modules\async\dist\async.js:3882:5)
    at Object.series (C:\Users\Nate\AppData\Roaming\nvm\v18.16.1\node_modules\ab-cli\node_modules\async\dist\async.js:4738:5)
    at C:\Users\Nate\AppData\Roaming\nvm\v18.16.1\node_modules\ab-cli\lib\utils\dockerStackWatch.js:70:13
  ```

2023-07-06 13:40 UTC, Hiro-Nakamura commented
Looks like we are having some problems with the tests.   The response implies that maybe the new `name: $STACKNAME` might not be getting a value for `$STACKNAME`.

2023-07-06 15:24 UTC, Hiro-Nakamura commented
ok, on my local machine, when I run this: the `docker-compose -f db init-compose.yml config > delme.yml` doesn't run properly with the `name: $STACKNAME` setting.

I get this error: 
```
The Compose file './dbinit-compose.yml' is invalid because:
'name' does not match any of the regexes: '^x-'

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

perhaps it is an OS issue?  If I remove the `name:` field, it works.  Maybe we need a different `version` ?

2023-07-06 15:36 UTC, Hiro-Nakamura requested changes
Been having some issues with the `name` parameter.

2023-07-07 07:06 UTC, nh758 commented
It seems like `docker-compose config` doesn't work consistently across OS?|

I'm able to bypass it and use `shelljs` to resolve the env variables. This works for me. Can you try it?

2023-07-17 06:22 UTC, merged